version: '3'

volumes:
  backend:
    driver: local
    driver_opts:
      type: none
      device: /root/ft_transcendence/backend/app
      o: bind
  frontend:
    driver: local
    driver_opts:
      type: none
      device: /root/ft_transcendence/frontend/front
      o: bind

networks:
  network:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 443:443
    restart: always
    networks:
      - network

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - backend:/app
    ports:
      - 8000:8000
    networks:
      - network
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/usr/src/app
    ports:
     - 423:423
    restart: always
    networks:
      - network
