# Generated by Django 4.2.3 on 2024-02-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='city',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AddField(
            model_name='ecole',
            name='country',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AddField(
            model_name='ecole',
            name='email',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AddField(
            model_name='ecole',
            name='password',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='first_name',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='last_name',
            field=models.CharField(default='none', max_length=60),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='username',
            field=models.CharField(default='none', max_length=60),
        ),
    ]
