# Generated by Django 4.2.3 on 2024-02-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topla', '0002_ecole_city_ecole_country_ecole_email_ecole_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='password',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
