# Generated by Django 4.2.3 on 2024-02-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topla', '0003_alter_ecole_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='profile_image',
            field=models.URLField(blank=True),
        ),
    ]
