# Generated by Django 4.2.3 on 2024-02-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topla', '0004_ecole_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecole',
            name='profile_image',
        ),
    ]
