# Generated by Django 4.2.3 on 2024-02-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topla', '0005_remove_ecole_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_images/'),
        ),
    ]
