# Generated by Django 4.2.3 on 2024-03-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topla', '0008_alter_ecole_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='enable2f',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecole',
            name='two_factor_code',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ecole',
            name='two_factor_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='profile_image',
            field=models.ImageField(default='img/default.jp', upload_to='profile_images/'),
        ),
    ]
