# Generated by Django 4.2.3 on 2024-03-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topla', '0009_ecole_enable2f_ecole_two_factor_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecole',
            name='two_factor_expire',
        ),
    ]
