# Generated by Django 4.2.3 on 2024-03-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topla', '0009_ecole_loginin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='loginIn',
            field=models.CharField(default='False', max_length=8),
        ),
    ]
