# Generated by Django 4.2.3 on 2024-03-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topla', '0013_alter_ecole_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='loginIn',
            field=models.CharField(default='False', max_length=8),
        ),
    ]
