# Generated by Django 4.2.3 on 2024-04-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topla', '0014_ecole_loginin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='two_factor_code',
            field=models.PositiveIntegerField(default='False'),
        ),
    ]
